version: '3'

volumes:
  postgres_data:
      driver: local

services:

  trace:
    container_name: trace
    image: openzipkin/zipkin
    restart: always
    ports:
      - "9411:9411"
    expose:
      - 9411
    networks:
      - backend

  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      networks:
        - backend

  keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:latest
      volumes:
      - ./imports:/opt/jboss/keycloak/imports
      command: 
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - "8080:8080"
      depends_on:
        - postgres
      networks:
        - backend

  # user:
  #   container_name: user
  #   image: httpsantos/user:1.0
  #   environment:
  #     EUREKA_URL: 'http://eureka:8761/eureka/'
  #     ZIPKIN_URL: 'http://trace:9411/'
  #   ports:
  #     - "8085:8085"
  #   expose:
  #     - 8085
  #   restart: always
  #   networks:
  #     - backend

  # delivery:
  #   container_name: delivery
  #   image: httpsantos/delivery:1.0
  #   environment:
  #     EUREKA_URL: 'http://eureka:8761/eureka/'
  #     ZIPKIN_URL: 'http://trace:9411/'
  #   ports:
  #     - "8084:8084"
  #   expose:
  #     - 8084
  #   restart: always
  #   networks:
  #     - backend

  # deal:
  #   container_name: deal
  #   image: httpsantos/deal:1.0
  #   environment:
  #     EUREKA_URL: 'http://eureka:8761/eureka/'
  #     ZIPKIN_URL: 'http://trace:9411/'
  #   ports:
  #     - "8081:8081"
  #   expose:
  #     - 8081
  #   restart: always
  #   networks:
  #     - backend

  # bid:
  #   container_name: bid
  #   image: httpsantos/bid:1.0
  #   environment:
  #     EUREKA_URL: 'http://eureka:8761/eureka/'
  #     ZIPKIN_URL: 'http://trace:9411/'
  #   ports:
  #     - "8083:8083"
  #   expose:
  #     - 8083
  #   restart: always
  #   networks:
  #     - backend

  # message:
  #   container_name: message
  #   image: httpsantos/message:1.0
  #   environment:
  #     EUREKA_URL: 'http://eureka:8761/eureka/'
  #     ZIPKIN_URL: 'http://trace:9411/'
  #   ports:
  #     - "8082:8082"
  #   expose:
  #     - 8082
  #   restart: always
  #   networks:
  #     - backend

networks:
  backend:
    driver: bridge
